### ISSUE TITLE
Home button on OSB projects...

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#1]
Moved from https://github.com/openworm/org.geppetto/issues/533...

When clicked, home button on right of OSB 3D view beside Persist button:

![selection_119](https://cloud.githubusercontent.com/assets/1556687/19350165/977b1a10-914e-11e6-8eb8-ef99017fad3f.png)

goes to this: 

![selection_121](https://cloud.githubusercontent.com/assets/1556687/19350297/0eb7f120-914f-11e6-900b-ef779c762ee9.png)

Maybe go to "Your models" tab if logged in, else go to OSB project main page? Or remove?

@tarelli What's your preferred repo for issues like this for Geppetto related OSB issues?

**Comment by mattearnshaw** [comment]
fixed with https://github.com/openworm/org.geppetto.frontend/commit/c867627bde812551ad2e117fbc4f406780a7b7c3 and https://github.com/OpenSourceBrain/redmine/commit/b74995295eba5bf58f189383969bdc937c555420

**Comment by tarelli** [comment]
The home button could also be removed (from redmine using the js channel) if the project is not one the user has already persisted.

**Comment by mattearnshaw** [comment]
that would probably be cleaner. for reference I have fixed this at https://github.com/OpenSourceBrain/redmine/commit/b74995295eba5bf58f189383969bdc937c555420 and  https://github.com/openworm/org.geppetto.frontend/commit/c867627bde812551ad2e117fbc4f406780a7b7c3 but will leave open for now

**Comment by pgleeson** [comment]
Might be best to just remove this, logged in or not. The user can get to the home page from outside this frame anyway, so no need to duplicate it here.

**Comment by mattearnshaw** [comment]
as suggested above https://github.com/OpenSourceBrain/redmine/commit/6c281f916e52c667beefdc9203e7ea2236f351bb
