### ISSUE TITLE
Floating scale bar for voltage colouring

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#10]
When the option 'Apply voltage colouring to morphologies' is selected, a pop up widget should appear showing the colour on the cells vs the membrane potential it represents. could be based on what's used in NEURON:

![selection_147](https://cloud.githubusercontent.com/assets/1556687/20667605/06ae4466-b562-11e6-83ec-8eda998273d4.png)

or neuroConstruct:

![selection_148](https://cloud.githubusercontent.com/assets/1556687/20667616/12045990-b562-11e6-96e4-54a7e94491e9.png)

**Comment by tarelli** [comment]
@mattearnshaw have a look at this https://plot.ly/python/heatmap-and-contour-colorscales/ could we reuse it?

**Comment by mattearnshaw** [comment]
@ 0.3.5
