### ISSUE TITLE
Enable [Ca2+] recording/replay on Geppetto

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#11]
In addition to asking to record all membrane potentials in somas/all segments, there should be an option to record the [Ca2+] level and replay this. 

Some example projects for this:
[Acnet](http://www.opensourcebrain.org/projects/acnet2?explorer=https%253A%252F%252Fraw.githubusercontent.com%252FOpenSourceBrain%252FACnet2%252Fmaster%252FneuroConstruct%252FgeneratedNeuroML2%252FMediumNet.net.nml)
[c302 (subset of cells)](http://opensourcebrain.org/projects/celegans?explorer=https%253A%252F%252Fraw.githubusercontent.com%252Fopenworm%252FCElegansNeuroML%252Fmaster%252FCElegans%252FpythonScripts%252Fc302%252Fexamples%252Ftemp_test%252Fc302_C_Pharyngeal.net.nml#)
[Blue Brain Project cell](http://opensourcebrain.org/projects/blue-brain-project-showcase?explorer=https%253A%252F%252Fraw.githubusercontent.com%252FOpenSourceBrain%252FBlueBrainProjectShowcase%252Fmaster%252FNMC%252FNeuroML2%252FcADpyr229_L23_PC_5ecbf9b163.stepcurrent3.net.nml#)

Note:

- Only give this option for cells which have internal Ca (the ComponentType for the cell will be `<cell>` and have `<species>`, see [here](https://github.com/openworm/CElegansNeuroML/blob/master/CElegans/pythonScripts/c302/examples/c302_C_Pharyngeal.nml#L74))
- Not all populations in the network and not all segments on the cell will have Ca present (e.g. only somas of pyramidal cells in Acnet)
- To be closer to what's usually recorded/analysed experimentally in Ca imaging, add option to colour cells during replay ranging from dark green to light green/yellow (e.g. [here](https://www.youtube.com/watch?v=XEy_WtgrF7A))

**Comment by mattearnshaw** [comment]
in progress eg. https://github.com/openworm/org.geppetto.frontend/commit/787fd99549eb94aacc79f882319829c7132b8172

**Comment by mattearnshaw** [comment]
@ 0.3.5
