### ISSUE TITLE
Update linked Izhikevich model

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#111]
Link to http://www.opensourcebrain.org/projects/izhikevichmodel?explorer=https%253A%252F%252Fraw.githubusercontent.com%252FOpenSourceBrain%252FIzhikevichModel%252Fmaster%252FNeuroML2%252FIzh2007Cells.net.nml

- [x] Save session with experiment data
- [x] Simulation of 0.8s
- [x] preassigned "use memb pot for colouring"
- [x] Add info widget as in old Izh example, explaining how to rerun 
- [x] Something like this when opened:

![selection_579](https://user-images.githubusercontent.com/1556687/35398901-ed667812-01ea-11e8-8e68-c63e922d780b.png)

**Comment by mattearnshaw** [comment]
live
