### ISSUE TITLE
Add session file as default for core OSB projects

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#112]
Network when Explore is hit should be reasonable sized network which loads quickly, along with info widget pointing to other important nets, incl ones from Figs

- [x] Allen (point to SomeCells2)
- [x] BlueBrain project (keep layer 2 cell, point to [this](http://www.opensourcebrain.org/projects/blue-brain-project-showcase/models#))
- [x] Vervaeke (keep this cell, add some ion channel plots)
- [x] Thalamocortical (keep Testsmall, point to TestMedium) also point to [this](http://www.opensourcebrain.org/projects/thalamocortical/models?explorer=https%253A%252F%252Fraw.githubusercontent.com%252FOpenSourceBrain%252FThalamocortical%252Fmaster%252FNeuroML2%252FpythonScripts%252FtestNetpyne%252FTestL23.net.nml) for Ca2+ example
- [x] Potj Diesmann (keep 2percent, say connections are slow to load)
- [ ] Hippocampal (don't have access to master at present...)
- [x] L2/3 cell: fine for now...
- [x] Migliore: [this](http://www.opensourcebrain.org/projects/miglioreetal14_olfactorybulb3d/models?explorer=https%253A%252F%252Fraw.githubusercontent.com%252FOpenSourceBrain%252FMiglioreEtAl14_OlfactoryBulb3D%252Fmaster%252FNeuroML2%252FNetworks%252FBulb_3MC_15GC_inputs.net.nml) can be loaded + explain how to record all segs + that it takes some time

**Comment by mattearnshaw** [comment]
stuff to confirm @pgleeson 
- [ ] I have written that TestSmall is 1% of the full network, and TestMedium is 10%. correct?
- [ ] which BBP to point to? link above doesn't show (I know why, should probably fix that)

**Comment by pgleeson** [comment]
Generally done, but better to keep this page up to date: http://www.comodl.org/projects/
