### ISSUE TITLE
Put limit on length of simulations

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#118]
The value of (num traces recorded * sim duration/ timestep) should be less than 4e6,
So for dt =0.025ms:
One cell recorded for 10 seconds
100 cells for 100ms each

This works out approx 100MB for max simulation

Give GUI warning on simulations that are too long, & suggest to get in contact if they need more resources. 

Limits don't apply to admins.

**Comment by mattearnshaw** [comment]
admin limits removed. closing but https://github.com/openworm/org.geppetto.frontend/issues/770 remains to be done
