### ISSUE TITLE
Add tutorial to repo

### ISSUE THREAD

**Issue by mattearnshaw** [OpenSourceBrain/geppetto-osb#12]
As opposed to fetching from dropbox:
https://github.com/OpenSourceBrain/geppetto-osb/blob/master/ComponentsInitialization.js#L117

**Comment by tarelli** [comment]
@mattearnshaw I've already done this on a branch https://github.com/OpenSourceBrain/geppetto-osb/tree/move_scripts will walk you through that tomorrow!
