### ISSUE TITLE
Continuous connections not loaded

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#122]
e.g. here: http://www.opensourcebrain.org/projects/celegans/models?explorer=https%253A%252F%252Fraw.githubusercontent.com%252Fopenworm%252FCElegansNeuroML%252Fmaster%252FCElegans%252FpythonScripts%252Fc302%252Fexamples%252Fc302_C0_Full.net.nml

There shoud be connections between neurons at centre and muscles

Also, that network is still quite slow to load... was this fixed on development?

**Comment by mattearnshaw** [comment]
both issues fixed on live (https://github.com/openworm/org.geppetto.model.neuroml/commit/ef04b8c4a4c68de29a261fad57345c4b01fa8c56). slow connections was due to "loading imports one at a time" which adds a lot of overhead when there are many… reverted for now
