### ISSUE TITLE
Plotting channel kinetics unavailable for some workflows

### ISSUE THREAD

**Issue by borismarin** [OpenSourceBrain/geppetto-osb#124]
It seems that the option for plotting channel kinetics only appears (n=1 observation...) if the cell which contains the channel is part of a network.
eg (HH tutorial): the links for plotting k-channel alphas/betas are available when exploring [HHCellNetwork.net.nml](http://opensourcebrain.org/projects/hodgkin-huxley-tutorial/repository/revisions/master/show/Tutorial/Source?explorer=https%253A%252F%252Fraw.githubusercontent.com%252Fopenworm%252Fhodgkin_huxley_tutorial%252Fmaster%252FTutorial%252FSource%252FHHCellNetwork.net.nml), but not when exploring [hh.cell.nml](http://opensourcebrain.org/projects/hodgkin-huxley-tutorial/repository/revisions/master/show/Tutorial/Source?explorer=https%253A%252F%252Fraw.githubusercontent.com%252Fopenworm%252Fhodgkin_huxley_tutorial%252Fmaster%252FTutorial%252FSource%252Fhhcell.cell.nml).

**Comment by mattearnshaw** [comment]
fix at https://github.com/openworm/org.geppetto.model.neuroml/commit/fad2feb73e1317926ab22d35856640e73c978d13 but not on live, @pgleeson does this fix seem sensible to you?

**Comment by mattearnshaw** [comment]
working on live with above commit and also https://github.com/NeuroML/neuroml2modelLite/commit/e80a2ca29d1e339c07d9d7063ba888f83b61dd97 workaround
