### ISSUE TITLE
Make min of y axis of rate plot 0Hz (not lowest rate value)

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#125]
Makes sense to see rates from 0Hz.. Top plot here makes it look at first glance like one population drops to zero firing...
![selection_660](https://user-images.githubusercontent.com/1556687/38434298-c220f246-39c5-11e8-8496-8929c4c2715c.png)

**Comment by mattearnshaw** [comment]
https://github.com/OpenSourceBrain/geppetto-osb/commit/e305f28beedd2d21427cc8ba2318ee4e569dab09
