### ISSUE TITLE
pubmed:xxx etc. in Readme files used to translate to link

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#128]
See http://www.opensourcebrain.org/projects/potjansdiesmann2014 for example
& http://www.opensourcebrain.org/docs#Write_Your_Project_Documentation for options

**Comment by mattearnshaw** [comment]
fixed/live at https://github.com/OpenSourceBrain/redmine/commit/65d3d59267695a037cd193d35638802bcafd4c9c
but method should be refactored
