### ISSUE TITLE
Voltage color scale seems to reset its axis after replay

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#130]
Seems to be set fine initially then y axis set to:

<img width="370" alt="screen shot 2018-04-18 at 15 48 51" src="https://user-images.githubusercontent.com/1556687/38939554-12ddeb04-4320-11e8-804f-d99fec588993.png">

after replaying (and switching dark->light->dark bkground)

**Comment by mattearnshaw** [comment]
live https://github.com/openworm/org.geppetto.frontend/commit/3cd0bca3e7089dc2e8dc35ff20c7abee21fbae3b
