### ISSUE TITLE
Use colour of population as colour of first variable plotted from that pop

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#141]
Related to https://github.com/OpenSourceBrain/geppetto-osb/issues/92...

Not just for "Plot all variables", also when a single plot is created from the control panel: if the population colour is red, use that as the colour of the trace in which is (manually) created. Colours for new traces in the same plot from cells of that population can be from the standard palette/random following this

**Comment by mattearnshaw** [comment]
to be deployed https://github.com/openworm/org.geppetto.frontend/commit/188175544b12411a4ae84757be430f2fe65de6bb
