### ISSUE TITLE
Clicking on "OSB best practice project" tag results in redmine 500

### ISSUE THREAD

**Issue by JustasB** [OpenSourceBrain/geppetto-osb#148]
For example on this page:
http://www.opensourcebrain.org/projects/l23dendriticspikes

clicking the tag, results in a Redmine error:
http://www.opensourcebrain.org/search_custom_field?f%5B%5D=35&op%5B35%5D=%3D&v%5B35%5D%5B%5D=2

**Comment by mattearnshaw** [comment]
working now, thanks @JustasB
