### ISSUE TITLE
Improve tree view on Explore page

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#149]
Long project names no longer displayed in full e.g. 

![selection_744](https://user-images.githubusercontent.com/1556687/41361333-bb542de8-6f26-11e8-8328-9a622dd538b0.png)

**Comment by mattearnshaw** [comment]
https://github.com/OpenSourceBrain/redmine/commit/9833075b315e5f53f68d35e76211dda4196aca46
