### ISSUE TITLE
Create a (stable-ish) development branch?

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#15]
It seems the master branch of this repo is no longer compatible with the latest in the main Geppetto repo development branches. It would be good to get a common development branch here so people can work of the latest version.

@gidili @jrmartin is the control-panel-extensions branch stable? Can a version of this be set as development for merger with @tarelli's move_scripts and some of @mattearnshaw's branches?

**Comment by gidili** [comment]
@pgleeson everything has been merged to development on org.geppetto.frontend, what may have happened is that the control-panel-extensions branch of this repo wasn't merged into the development branch, if we do that (can do today) then we're all set to work on development for everything, and we merge into master when we release as usual.

**Comment by tarelli** [comment]
Created this https://github.com/OpenSourceBrain/geppetto-osb/tree/development. It includes move_scripts and control-panel-extensions.

**Comment by pgleeson** [comment]
Excellent! Just what I needed! Thanks.
