### ISSUE TITLE
Fix Add & Run Protocol

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#150]
Currently a protocol can be run on a single cell network with a current input, but this example fails:
http://www.opensourcebrain.org/projects/wangbuzsaki1996/models?explorer=https%3A%2F%2Fraw.githubusercontent.com%2FOpenSourceBrain%2FWangBuzsaki1996%2Fmaster%2FNeuroML2%2FLEMS%2FWangBuzsaki.net.nml

I believe it assumes the pulse generator is called pulseGen1, but in general if there is a single pulse generator input to the network, that should be used. 
~~If it can't find it, a more specific error should be given.~~

In many cases there's a valid reason to have 2 inputs, e.g. [here](https://github.com/OpenSourceBrain/BlueBrainProjectShowcase/blob/master/NMC/NeuroML2/cADpyr229_L23_PC_5ecbf9b163.stepcurrent3.net.nml) there is a hyperpolarizing current for the whole sim, but a transient depolarising current pulse which should be the one altered. In the best scenario, a user is given details of the 2+ currents (i.e. times & amplitude), and asked which of them to alter (and ideally given an option to leave the rest as is or set them to zero).

![selection_745](https://user-images.githubusercontent.com/1556687/41414405-c8dc0f14-6fdd-11e8-809c-d650d9efb4ef.png)

**Another potential issue**: there is no indication of the step between current levels, there should be an option for interval or number of steps between max & min

![image](https://user-images.githubusercontent.com/1556687/46882417-876e8580-ce46-11e8-86a0-b3d26598e17e.png)

**Comment by mattearnshaw** [comment]
notes

`Model.neuroml.wb1.IClamp.getType().getSuperType().getName()` == `pulseGenerator`
so need "getAllTypesOfSuperType" commented out at https://github.com/openworm/org.geppetto.frontend/blob/master/src/main/webapp/js/geppettoModel/ModelFactory.js#L2436

**Comment by pgleeson** [comment]
@mattearnshaw this will be needed for the new pyramidal cell tutorial...

**Comment by mattearnshaw** [comment]
first impl @ https://github.com/OpenSourceBrain/geppetto-osb/commit/23eedd806ef7a535e46a28bf0ec1296111500760, requires pulls on `model.neuroml` and `frontend`

**Comment by mattearnshaw** [comment]
comodl
