### ISSUE TITLE
Coloured dot on Experiments tab missing

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#151]
![selection_746](https://user-images.githubusercontent.com/1556687/41458720-4ce7202c-707f-11e8-95fc-a4ce51d994d0.png)

**Comment by mattearnshaw** [comment]
to be deployed at https://github.com/OpenSourceBrain/geppetto-osb/commit/223d7e687fd838db909ccc654a17198cfe47ddd7
