### ISSUE TITLE
Updated Experiments tab half showing & not working well with OSB intro tutorial widget

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#156]
- only partially shown

<img width="361" alt="screen shot 2018-07-07 at 10 21 56" src="https://user-images.githubusercontent.com/1556687/42409249-9c8d80ce-81cf-11e8-850e-d80e1eed2623.png">

- Doesn't pop up on intro tutorial screen explaining experiments table
- Prob possibly due to adding orange circle back

<img width="312" alt="screen shot 2018-07-07 at 10 23 50" src="https://user-images.githubusercontent.com/1556687/42409273-dca05ea2-81cf-11e8-8c55-8b452c36a473.png">

**Comment by mattearnshaw** [comment]
tabs fixed, tutorial actions working but seems now not to show the corresponding messages…

**Comment by mattearnshaw** [comment]
fix for disappearing actions to be merged at https://github.com/openworm/org.geppetto.frontend/pull/818/files
