### ISSUE TITLE
Check turtorial widgets

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#157]
Content of tutorials not showing at http://www.opensourcebrain.org/projects/hodgkin-huxley-tutorial?explorer=https%3A%2F%2Fraw.githubusercontent.com%2Fopensourcebrain%2Ftutorials%2Fdevelopment%2Fmodels%2FhodgkinHuxley%2FGEPPETTO.json

**Comment by mattearnshaw** [comment]
have reverted tutorial for now, so is displayed everywhere, but needs further investigation since two steps are skipped in the OSB tutorial.
