### ISSUE TITLE
Trace of first cell in population is same colour as population; rest should be random/sequential

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#158]
Currently all are same colour within population:

![image](https://user-images.githubusercontent.com/1556687/43200323-1ba239ae-900d-11e8-921b-d17ddc1d4d81.png)

**Comment by mattearnshaw** [comment]
https://github.com/OpenSourceBrain/geppetto-osb/commit/db31ffd599793ef4b35a794d3f549b33ee6d7856
