### ISSUE TITLE
Add "Create new experiment" option to Run dropdown menu

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#165]
..which will copy current (completed) experiment, ready to be rerun when that menu is selected again

- [x] add Create new experiment option
- [x] add menu item "Sign up and log in to run experiments" when user not logged in. When clicked, takes user to http://www.opensourcebrain.org/login. When logged in this menu item disappears...

**Comment by gidili** [comment]
@pgleeson if it's duplicating an existing one so that it can be re-run perhaps "Clone experiment"?

**Comment by pgleeson** [comment]
Technically that's what it would do, but just looking at it from the point of view of a naive user who doesn't even know what an experiment is... 

At the moment they'd see a disabled Run option & would search for a while to find the clone experiment option. "Create new experiment" should be clear for them as to what will happen next.  

Would be good to also make it clear here that the user needs to log in...

**Comment by mattearnshaw** [comment]
(to be deployed on comodl)
