### ISSUE TITLE
Add thumbnail images/brief description to http://www.opensourcebrain.org/projects

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#168]
To make a more inviting entry point for core scientific models.

Would be ideal to generate this automatically from a JSON file with:
- Category (Neocortex, Cerebellum, etc)
   - Project name
   - Link to OSB project
   - Link to 3D view (figure in paper ideally...)
   - Description
   - image URL

to ease addition of new project/redesign of page

**Comment by mattearnshaw** [comment]
first version on `review` branch of redmine https://github.com/OpenSourceBrain/redmine/commit/953a8c065daa778d4af2c66c878b473def782a8d

**Comment by pgleeson** [comment]
Live on comodl
