### ISSUE TITLE
Test public sharing of projects

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#17]
Currently I can click bottom right to share project (and get URL) when I'm not logged in

**Comment by tarelli** [comment]
Yep, we need to find a way around that, the OSB anonymous user is logged in :)

**Comment by pgleeson** [comment]
Not working on comodl... Sharing icon on bottom right does not become enabled when I persist a project.
I tried reloading a project, it was enabled but pressing it led to:

![selection_284](https://user-images.githubusercontent.com/1556687/26839143-0e7c238a-4ada-11e7-9214-1525efca0ab3.png)

**Comment by tarelli** [comment]
@pgleeson let me have a look with @mattearnshaw redmine is not passing to geppetto the url in some scenarios then (that undefined)

**Comment by pgleeson** [comment]
Changed title to generally making sure sharing of project is working on live (& comodl)

**Comment by mattearnshaw** [comment]
working on comodl with:
https://github.com/OpenSourceBrain/redmine/pull/304, https://github.com/OpenSourceBrain/geppetto-osb/pull/79
to be merged

**Comment by mattearnshaw** [comment]
working on live
