### ISSUE TITLE
Disable Results menu items if experiment in design state

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#170]
No entries here can be used if there's no results saved yet:
![image](https://user-images.githubusercontent.com/1556687/48408161-8d4ed380-e730-11e8-92a1-4e1b562cf400.png)
It's disabled before project is persisted, but enabled afterwards. Best to tie this to state of experiment & only enable if current experiment completed.

**Comment by mattearnshaw** [comment]
comodl
