### ISSUE TITLE
Sign up for Google Cloud computing

### ISSUE THREAD

**Issue by tarelli** [OpenSourceBrain/geppetto-osb#180]
- [x] Create a new free tier Codefresh account. Create the new Google cloud account also from codefresh (link https://codefresh.io/google-cloud/?utm_source=SumoMe&utm_medium=Banner&utm_campaign=SM2) to get $500 free credit instead of $300
- [x] Create a new Google cloud computing account for the lab (should be done as part of the point above)
- [x] Add permissions

**Comment by tarelli** [comment]
@pgleeson can you create a new account for the lab and for now give admin access to matteo@metacell.us filippo@metacell.us and facundo@metacell.us You will have $300 credit because it's a new account, that should be enough to cover for these initial months of testing.

**Comment by pgleeson** [comment]
Have created an account silverlabcloud on codefresh and silverlabcloud@goog. seem to just have $300 credit with GCloud. 

I assume you mean add you as collaborators at People on Codefresh?

**Comment by tarelli** [comment]
@pgleeson on both codefresh and google cloud engine (not everything is possible from codefresh) in the IAM members section with the permissions Kubernetes Engine Cluster Admin, Kubernetes Engine Developer, Logs Viewer. Let me know if you need help with this.

**Comment by pgleeson** [comment]
Done I believe...
