### ISSUE TITLE
Evaluate how much work is required for the NWB-Explorer to work with any files

### ISSUE THREAD

**Issue by tarelli** [OpenSourceBrain/geppetto-osb#184]
We need to make sure that all the timeseries are been loaded and are properly plotted.

Test NWB explorer with
- [ ] https://github.com/OpenSourceBrain/NWBShowcase/blob/master/FergusonEtAl2015/TestData.ipynb 
- [ ] https://github.com/OpenSourceBrain/NWBShowcase/blob/master/TriplettEtAl2018/TestDataset.ipynb

**Comment by filippometacell** [comment]
Tested the NWBModelInterpreter following files with the last pynwb and the results are not really exciting

- https://github.com/OpenSourceBrain/NWBShowcase/blob/master/NWB/time_series_data.nwb' - pynwb error: incorrect type for 'keywords' (got 'str', expected 'ndarray, list, tuple, Dataset, AbstractDataChunkIterator or FORMDataset'
- https://github.com/OpenSourceBrain/NWBShowcase/blob/master/NWB/simple_example.nwb: loads without errors
- https://github.com/OpenSourceBrain/NWBShowcase/blob/master/FergusonEtAl2015/FergusonEtAl2015.nwb- pynwb error: incorrect type for 'keywords' (got 'str', expected 'ndarray, list, tuple, Dataset, AbstractDataChunkIterator or FORMDataset'
- http://ec2-34-229-132-127.compute-1.amazonaws.com/api/v1/item/5ae9f7896664c640660400b5/download - No specification for 'ROITableRegion' in namespace 'core'. This file worked in with previous versions of pynwb and was used to showcase nwb explorer.
