### ISSUE TITLE
Design how to organise the codebase. Where does the Python NWB model interpreter go? 

### ISSUE THREAD

**Issue by tarelli** [OpenSourceBrain/geppetto-osb#185]

**Comment by filippometacell** [comment]
At this moment the nwb model interpreter is a Python module within the nwb-explorer umbrella application, which is fine until we go for a deeper integration.
A positioning could be more properly discussed after a more general refactoring and decisions about pygeppetto.
In particular, we need the aswer to this specific question:
- should the model interpreters and other Geppetto components be dynamically loaded as in the Java backend?

**Comment by pgleeson** [comment]
Probably well out of date...
