### ISSUE TITLE
Design how a NWB file contained inside a GitHub repository linked to an OSB project can be opened using the embedded NWB-Explorer

### ISSUE THREAD

**Issue by tarelli** [OpenSourceBrain/geppetto-osb#189]

**Comment by filippometacell** [comment]
Preliminar analysis: 
1. OSB ask to JupyterHUB a new instance to use with NWBE or NetPyNE
1. The instance is spawned and the address is returned to OSB, which caches the address for further user accesses.
1. OSB calls the NWBE REST api  passing the (public) github address - namely /api/load?nwbfile=[URL]

**Comment by pgleeson** [comment]
@mattearnshaw has created a demo with this...
