### ISSUE TITLE
Use colour info in population tag in NeuroML 

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#19]
See https://github.com/OpenSourceBrain/redmine/issues/244

**Comment by mattearnshaw** [comment]
in `0.3.6`

**Comment by pgleeson** [comment]
While `<>`

**Comment by mattearnshaw** [comment]
fix at https://github.com/openworm/org.geppetto.model.neuroml/pull/127/files, to be reviewed

**Comment by borismarin** [comment]
apropos, as per #46, what's the current (geppetto) API for getting the `color` for a given pop?

**Comment by mattearnshaw** [comment]
@borismarin `path.getColor` should work- there isn't anything in the NeuroML model interpreter (yes, still calling it that) for this like you mention, but I think this can all be done from the frontend?

**Comment by borismarin** [comment]
@mattearnshaw thanks
yes, everything there is frontend, no need to touch the nml model interpreter

**Comment by borismarin** [comment]
@mattearnshaw I'm  also surprised that @tarelli took this violation of MVC lightly...

**Comment by tarelli** [comment]
@borismarin ModelInterpreter can contribute a defaultView defined in the project, nothing to do with the GeppettoModel 👍 💯

**Comment by mattearnshaw** [comment]
merged at #127
