### ISSUE TITLE
How will Open Source Brain talk to embedded JupyterHub deployments?

### ISSUE THREAD

**Issue by tarelli** [OpenSourceBrain/geppetto-osb#190]
- [x] Answer these question (here or in a doc): are we going to add REST APIs to Geppetto Jupyter applications? How to do this?
- [x] We should pay attention to the fact that these APIs will have to be meaningful also without considering OSB to not introduce a conceptual dependency
- [x] If services is the way to go present a proposal for the interface agreements amongst the different components

**Comment by filippometacell** [comment]
We're embedding Jupyter hub applications inside OSB as iframes.
Jupyter hub spawns the application instance in a sub path of the original address.
For instance, starting from http://ADDR the actual application will be on http://ADDR/user/[UUID].
So is not straightforward where the application actually is from the parent iframe.
The solution which has been implemented is the following:
1. When the iframe redirects we can catch from the parent iframe through the event `onLoad`
1. We can send a message to the child iframe through `frame.contentWindow.postMessage`
