### ISSUE TITLE
Deploy NetPyNE to OSB Kubernetes

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/geppetto-osb#198]
- [x] Create a new pipeline to build a Dockerfile with Jupyter Hub for NetPyNE (https://github.com/MetaCell/NetPyNE-UI/tree/feature_jupyterhub)
- [x] Configure the cluster (tiller, helm, etc.)
- [x] Create a new helm chart for netpyne-ui
- [x] Test the new service works

**Comment by rodriguez-facundo** [comment]
I am facing some issues in the deployment when I have to specify the context for HELM. 
usually you make HELM aware of the context by context: 'my-cluster-name@my-project-name'

Now, this particular project has some white spaces in the name and the installation fails with error 'no context found'. I will update as soon as I get the context right

**Comment by rodriguez-facundo** [comment]
all set 35.193.158.86
