### ISSUE TITLE
Allow Geppetto to read in HDF5 based network descriptions

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#20]
Example in here: https://github.com/OpenSourceBrain/NetPyNEShowcase/tree/master/NeuroML2/scaling

Initial Java reader for this format: https://github.com/NeuroML/org.neuroml.model/blob/development/src/main/java/org/neuroml/model/util/hdf5/NeuroMLHDF5Reader.java, though currently better supported read/write in Python: https://github.com/NeuralEnsemble/libNeuroML/tree/development/neuroml/hdf5

See status of NML2/HDF5 format here: https://github.com/NeuroML/NeuroML2/issues/93

More details to follow...

**Comment by pgleeson** [comment]
- [ ] Add NeuroMLDocumentOptimized to org.neuroml.model with internal arrays of conn data taken from HDF5 file and a method for getConnection(name, index)
- [ ] Update NeuroMLModelInterpreterServiceTest to load multiple NML2 files, and directly compare size etc. of connections in NML object tree & Geppetto equivalent
- [ ] Update OptimizedLEMSReader to store NeuroMLDocumentOptimized
- [ ] Use this to extract position/connection info e.g. for createPopulationTypeVariable(), extractConnection()

**Comment by mattearnshaw** [comment]
h5 files loading on OSB (including connections) with the following branches
- redmine `hdf5`
- org.geppetto.model.neuroml `pg_hdf5`
- org.neuroml.model `hdf5`

**Comment by pgleeson** [comment]
Working! Close when on live...

**Comment by mattearnshaw** [comment]
now on live and comodl
