### ISSUE TITLE
Passing the URL parameter to NWB explorer

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/geppetto-osb#203]
We want to implement this behaviour inside OSB:
1. Inside a OSB project, the user clicks on a *.NWB file, say MYFILE.NWB
1. OSB calls Jupyter HUB which spawns an instance with NWB explorer
1. OSB gets the addredd and stores the address in the session - namely NWBE_ADDRESS
1. OSB calls NWBE_ADDRESS/api/load?nwbfile=http://MY_PUBLIC_REPO/.../MYFILE.NWB

**Comment by filippometacell** [comment]
We can load a file from parameter inside NWB Explorer. Next step, make it work from Jupyter Hub
