### ISSUE TITLE
Avoid restarting the kernel when loading the extension

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/geppetto-osb#207]
See index.js. At first this was needed to restart NEURON.

- [ ] analyse the jupyter extension loading code -- meeting

**Comment by filippometacell** [comment]
Update: the whole process behind the extension loading should be changed. It's starting a standard project loading and experiment from inside the extension. This prevents to implement simpler workflows, as it's happening in NWB Explorer.
As a solution, we may leave all the logic outside the extension, in the 'jupyter_geppetto_extension_ready' event callback inside the ComponentInitialization.

**Comment by filippometacell** [comment]
The Jupyter extension has been simplified:
- removed the kernel restart
- removed the geppetto project/experiment load

If needed, these functionalities can be moved on the application responding at the event jupyter_geppetto_extension_ready
