### ISSUE TITLE
Move NWB explorer prototype to new geppetto project structure

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/geppetto-osb#208]
Geppetto projects have changed the structure with the split of the frontend from the backend.
Move the applicatio prototype to the new structure without changing functionality.

**Comment by filippometacell** [comment]
Working setup:
jupyter geppetto commit 12e321e91602daf635ef2e7a0c1fca48348889ff
nwb explorer commit ce77c4672de057e109de83d4a7bd2f8971d293b5
geppetto nwb-explorer commit 1017d6e3891f61789122df6f0cdb26e18544fe7f
