### ISSUE TITLE
Allow NWB explorer to work within a JupyterHUB instance

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/geppetto-osb#209]
The instance of Geppetto running within JupyterHUB needs to be adapted in order to run within the contextPath which is being assigned by the hub (--/user/[pseudo-random-id]).
This has been addressed with a patch by Adrian which needs more work to be integrated in a general framework https://github.com/openworm/org.geppetto.frontend.jupyter/pull/57, https://github.com/openworm/org.geppetto.frontend/pull/859.
There are different branches to merge and issues to be addressed, which are not so trivial.
See a general discussion here: https://github.com/openworm/org.geppetto/issues/609

**Comment by filippometacell** [comment]
The first thing I'd do here is to centralize the path constructing within Geppetto, i.e. delegating that to a PathService which takes care of resolving all the paths for the application.
The first implementation could follow the solution proposed in the first implementation, i.e. asking the path to the window.

**Comment by filippometacell** [comment]
HDFView helps in looking at the content. We can recognise a time series from the presence of a "data" dataset within a group. A timestamps variable is also usually there, although it can be replaced from the "rate" variable specification on the group.
Example: ![image.png](https://images.zenhubusercontent.com/5c4f23c24557275e4b89d83b/5c0bebb3-a4cf-4d79-8778-6ea7de6cc0a4)

- https://github.com/OpenSourceBrain/NWBShowcase/blob/master/NWB/time_series_data.nwb: One time series with a sine
- https://github.com/OpenSourceBrain/NWBShowcase/raw/master/NWB/simple_example.nwb: no time series
https://github.com/OpenSourceBrain/NWBShowcase/raw/master/FergusonEtAl2015/FergusonEtAl2015.nwb: 60 time series, plotted each one separately (@pgleeson we are not supporting getting them grouped as in https://github.com/OpenSourceBrain/NWBShowcase/blob/master/FergusonEtAl2015/TestData.ipynb by now)
YutaMouse41-150903.nwb (5GB): 20 linear time series. Some of the time series are being splitted from multi dimensional time series

**Comment by filippometacell** [comment]
?nwbfile=[url_or_path] from jupyter hub to nwb explorer
