### ISSUE TITLE
First integration between OSB and NWB explorer

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/geppetto-osb#212]
With this first integration we Just open a new instance of NWB Explorer in a new tab when clicking on a nwb file.
We don't pass the url yet, the loaded file will be always the same for now and determined statically.

**Comment by pgleeson** [comment]
Reopening... Was working in some branch of Matt's but the basic loading in a new tab should work from clicking one of the green eyes in a page like this:
http://www.opensourcebrain.org/projects/nwbshowcase/repository/revisions/master/show/FergusonEtAl2015

**Comment by filippomc** [comment]
Sorry but this issue didn't really said about ongoing work, I remembered that was working! I'm trying to close whatever I know something about to figure out something in the mess of a lot of unclosed issues that we have. Could you please help me by closing/respecifying all the outdated stuff in the osb-geppetto and redmine repos? Maybe closing everything and opening new issues for the bugs can be easier..

**Comment by filippomc** [comment]
Addressing this in the following issue on nwb-explorer: https://github.com/MetaCell/nwb-explorer/issues/134

**Comment by pgleeson** [comment]
Ok, will go through the issues in the next few days and assign any to you if they're relevant for the new contract, otherwise will be closed or done at ucl.

**Comment by filippomc** [comment]
Thanks that will help a lot!
