### ISSUE TITLE
Resolve iframe cross-origin issue with NetPyne

### ISSUE THREAD

**Issue by filippometacell** [OpenSourceBrain/geppetto-osb#215]
Add header: Access-Control-Allow-Origin: http://opensourcebrain.org/

We can suppose it can be set in the config as usual --> embeddedUrl in https://github.com/MetaCell/NetPyNE-UI/blob/master/utilities/GeppettoConfiguration.json

We may have to deal also with Jupyter Hub, which is not reading the configuration file.

**Comment by rodriguez-facundo** [comment]
Hi @mattearnshaw, I think it is ready now 

<iframe src="http://35.193.158.86:80" />

**Comment by mattearnshaw** [comment]
@rodriguez-facundo thanks – that should work for the live site, could you also allow `localhost:3000` and `comodl.org` for testing?

**Comment by facurod** [comment]
Hi @mattearnshaw :
- localhost:3000
- http://comodl.org:80
- http://opensourcebrain.org:80

are now allowed to iframe netpyne

**Comment by mattearnshaw** [comment]
thanks!
