### ISSUE TITLE
Some tweaks

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#216]
- [x] Add info "These are just a selection of some stable, well tested projects on OSB. To see all projects click [here](http://www.opensourcebrain.org/projects#cells)" to top of http://www.opensourcebrain.org/projects
- [x] Replace arrow on 4 panels on homepage and test that text on these doesn't cover images when browser window is narrowed
- [x] from http://www.opensourcebrain.org/tutorials, the L23 tutorial has "Hodgkin Huxley Tutorial " at top of screen...

**Comment by mattearnshaw** [comment]
live

**Comment by pgleeson** [comment]
Add git repos: http://www.opensourcebrain.org/projects/vervaekeetalgolgicellnetwork/repository

**Comment by mattearnshaw** [comment]
whoops, changed how this works earlier (to make this situation not happen, but didn't pull the commit...)

**Comment by pgleeson** [comment]
Link at top of http://localhost:3000/projects doesn't display all projects (should ideally switch selection in menu on left to "All Cell & networks" also)
