### ISSUE TITLE
Prepare OSB continuous integration test/staging environment on Kubernetes

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/geppetto-osb#217]
The test environment is aligned with the branch `feature_netpyne_nwb_first_integration` of the OSB project.
All the related projects (i.e. Geppetto etc) come with  the same branch name or development.

- [x] set up the docker files
- [x] get familiar with Kubernetes (with Facundo)
- [ ] set up the test environment on test.opensourcebrain.org
- [ ] set up the staging environment on beta.opensourcebrain.org

**Comment by filippometacell** [comment]
For the domain, we're thinking o staging.opensourcebrain.org, staging.comodl.org, osbstaging.comodl.org
@pgleeson any preference?

**Comment by pgleeson** [comment]
Maybe better use beta.opensourcebrain.org, in case we want to give it to anyone else to test/look at...

**Comment by filippometacell** [comment]
OK. I didn't consider the possibility that we can have someone from outside testing/watching is potentially dangerous. I'd go with two environments in this case, one proper staging on beta.opensourcebrain.org, with manually triggered update with whatever we want, and one test environment (say test.comodl.org) just for ourselves which is continuosly updated on the branch `feature_netpyne_nwb_first_integration`. @tarelli what do you think?

**Comment by tarelli** [comment]
It makes sense, let's discuss maybe briefly at the meeting later.

**Comment by filippometacell** [comment]
Hi @mattearnshaw, have you started with something?

**Comment by mattearnshaw** [comment]
test cluster in progress, codefresh side to be set up tomorrow
