### ISSUE TITLE
Agree a minimal set of supported files

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/geppetto-osb#218]
- [x] Ask the pyNWB team to ask some test files (use slack)
- [x] Ask the pyNWB team to ask some real files, if available (use slack)
- [ ] Agree with Padraig the minimal set of files which we want to support at the conference.

**Comment by filippometacell** [comment]
A satisfying first group of files has been detected.
TODO share files and get a look with Padraig

**Comment by filippometacell** [comment]
We have this list of working files:
- https://github.com/OpenSourceBrain/NWBShowcase/blob/master/NWB/time_series_data.nwb
- https://github.com/OpenSourceBrain/NWBShowcase/raw/master/NWB/simple_example.nwb
- https://github.com/OpenSourceBrain/NWBShowcase/raw/master/FergusonEtAl2015/FergusonEtAl2015.nwb
- YutaMouse41-150903.nwb (5GB), ask me for the url (we have been asked to not to make the url public)
