### ISSUE TITLE
Define expected visible content for each of the test files

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/geppetto-osb#222]
- [x] Ask Padraig for the files he's creating
- [x] Be more familiar with the format
- [x] Define the timeseries we expect for each file

**Comment by filippometacell** [comment]
Look at the python notebooks

**Comment by filippometacell** [comment]
HDFView helps in looking at the content. We can recognise a time series from the presence of a "data" dataset within a group. A timestamps variable is also usually there, although it can be replaced from the "rate" variable specification on the group.
Example: ![image.png](https://images.zenhubusercontent.com/5c4f23c24557275e4b89d83b/5c0bebb3-a4cf-4d79-8778-6ea7de6cc0a4)

- https://github.com/OpenSourceBrain/NWBShowcase/blob/master/NWB/time_series_data.nwb: One time series with a sine
- https://github.com/OpenSourceBrain/NWBShowcase/raw/master/NWB/simple_example.nwb: no time series
https://github.com/OpenSourceBrain/NWBShowcase/raw/master/FergusonEtAl2015/FergusonEtAl2015.nwb: 60 time series, plotted each one separately (@pgleeson we are not supporting getting them grouped as in https://github.com/OpenSourceBrain/NWBShowcase/blob/master/FergusonEtAl2015/TestData.ipynb by now)
YutaMouse41-150903.nwb (5GB): 20 linear time series. Some of the time series are being splitted from multi dimensional time series
