### ISSUE TITLE
Connect loaded nwb file with Jupyter notebook

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/geppetto-osb#235]
We want to find the loaded file on the Jupyter notebook, say from variable 'nwbfile'.
This is tougher than initially expected, because the backend server and the notebook run on different Python Kernels.
This leads to the fact that when we're loading the file from the rest API the notebook cannot see it.
We have different alternatives:
- Replace REST APIs with calls to the jupyter backend through IPython js variable as other applications are doing with synchronization
- Find a way to use the notebook kernel the application apis
- Find a way to share the kernel between the server and the notebook
- Transfer the data through serialization (e.g. pickle)

**Comment by filippometacell** [comment]
The file is loaded separately from the backend into the kernel.
We could need a synchronization at one point
