### ISSUE TITLE
Add meta data to NWB Explorer

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/geppetto-osb#237]
@pgleeson maybe we want to show some meta data for the first release?

**Comment by pgleeson** [comment]
Sure, maybe oan overview of the number of sweeps/stimuli, and the data on experimenter/lab presnet under the general group. Think this is done to some extent in the prototype NWB explorer already...

**Comment by filippometacell** [comment]
We have nothing yet in the current Python implementation. The old Java nwb1 example was more complete in this sense: https://live.geppetto.org/geppetto?load_project_from_id=18. Maybe we can start reasoning from here?

**Comment by pgleeson** [comment]
Yes, it was the NWB1 version I meant...
