### ISSUE TITLE
Explore pynwb legacy mode

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/geppetto-osb#241]
The legacy mode allows to load old nwb1 files, see here: https://github.com/NeurodataWithoutBorders/pynwb/issues/275

- [ ] Try to load some elecrophysiology files from Allen institute like https://celltypes.brain-map.org/experiment/electrophysiology/643625553
- [ ] Check if after the file is loaded there's need to more work to make it work on NWB explorer

**Comment by pgleeson** [comment]
The issue of all the old NWBv1 files is well known to Allen I'm sure, and we can assume there will be a bulk conversion at some stage.

I think support for NWBv1 is low priority and may only complicate things going forward... There are not too many NWBv1 files out in the wild besides Allen's anyway...

**Comment by filippometacell** [comment]
The issue on pynwb is still open and apparently nothing is coming soon on that side.
Shall we wait to some conversion?
