### ISSUE TITLE
NWB explorer: show general content information

### ISSUE THREAD

**Issue by filippometacell** [OpenSourceBrain/geppetto-osb#242]
When the file is loaded a widget shows general information about the content of the experiment.
The data we show is coming from the general section of the NWB file.
We can add also some aggregated information, for instance:
- Number of acquisition, stimuli, processing modules

Use as starting point what we have in metadata and description widgets here:
https://live.geppetto.org/geppetto?load_project_from_id=18

**Comment by filippometacell** [comment]
@pgleeson please integrate with anything I have missed at this level (we're not thinking about how data is related here yet)

**Comment by pgleeson** [comment]
@filippometacell This (and possibly some other issues) should eventually become something like: Create NWB file main control panel... The first widget/panel the user sees when an NWB file is loaded. Eventually it could have custom functionality for quickly getting an overview of all of the data (and intelligently linking all the stimuli/sweeps/images) & be very experimentalist friendly...

**Comment by filippometacell** [comment]
@pgleeson do you mean you'd like the issues more like use cases form in general? I've revised this issue, please let me know if I've got the point!
