### ISSUE TITLE
SWC interpreter missing in live?

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#248]
e.g. http://www.opensourcebrain.org/projects/neuromorpho/models?explorer=https%253A%252F%252Fraw.githubusercontent.com%252FOpenSourceBrain%252FNeuroMorpho%252Fmaster%252FSWC%252F04a_pyramidal4aACC.CNG.swc

![image](https://user-images.githubusercontent.com/1556687/56230956-377eae80-6075-11e9-9797-948702f79a44.png)

**Comment by mattearnshaw** [comment]
added to plan and deployed
