### ISSUE TITLE
Add ssl on website

### ISSUE THREAD

**Issue by rodriguez-facundo** [OpenSourceBrain/geppetto-osb#253]
OSB k8s deployment has ssl certification set on www.facu-test.com.

The IP for the k8s deployment is 34.66.101.97

When this IP is set for the real DNS, we will replace facu-test.com

**Comment by rodriguez-facundo** [comment]
We added ssl certification for OSB website. The technology is:

- let's encrypt
- cert-manager
- nginx-ingress controller

The process is automated, so there is not need to worry about expiration dates or renewals. The current DNS was set to www.facu-test.com just until the real DNS is assigned to IP 34.66.101.97

**Comment by rodriguez-facundo** [comment]
I hit a limit on the number of certificates issued for facu-test.com, so I need to wait a week for the renewal. A resume of what I have done so far:

- A nginx controller seats in front of the cluster. The nginx IP is mapped to all the domains and subdomains I want to pipe to this nginx controller, example: facu-test.com, www.facu-test.com, geppetto.facu-test.com, etc. (they are all A class)
- A ingress is created to send the request to the appropriated service:
   facu-test.com goes to redmine:80, geppetto.facu-test.com goes to geppetto:8080, etc.
- If OSB gets ssl, then geppetto needs ssl if we want to iframe it and to keep the ssl for osb.
- Geppetto need to get the following settings for embedding and ssl:
  - useSSL: true
  - embedded: true
  - embeddedURL: https://facu-test.com
- osb-redmine need to be build with the following props:
  - SERVER_IP=https://facu-test.com/
  - GEPPETTO_IP=https://geppetto.facu-test.com/
  - Note the / at the end and there is no port specification because ingress already knows the correct port.
- Geppetto need to have an external IP, it cannot be referenced with a cluster internal IP.

For now, we have:
- the nginx server without ssl.
- redmine container build with:
  - SERVER_IP=http://facu-test.com/
  - GEPPETTO_IP=http://geppetto.facu-test.com/
- geppetto container build with
  - "embedded":  http://facu-test.com
  - "usessl": false
  - "url": http://facu-test.com

**Comment by rodriguez-facundo** [comment]
Hi @pgleeson, can you set this IP for OSB beta domain: 35.226.216.111

The idea is to have:
- domain.com
- geppetto.domain.com
 
or maybe:
- beta.domain.com
- geppetto.domain.com

This is my test domain configuration ![Screenshot 2019-05-29 at 1.04.12 PM.png](https://images.zenhubusercontent.com/5bfd7568a6759a229d994d6a/077db7cb-25a0-410b-b5dc-93c239091b19)

**Comment by filippometacell** [comment]
To put it clear: 

- beta.opensourcebrain.com -> 35.226.216.111 
- geppetto.beta.opensourcebrain.com -> 35.226.216.111

**Comment by pgleeson** [comment]
Did you mean (note .org):
beta.opensourcebrain.org -> 35.226.216.111      (done already)
geppetto.opensourcebrain.org -> 35.226.216.111

**Comment by filippometacell** [comment]
yes .org sorry

**Comment by filippometacell** [comment]
I wouldn't take geppetto.opensourcebrain.org for the staging environment, that's why geppetto.beta.opensourcebrain.org

**Comment by pgleeson** [comment]
Ok, http://geppetto.beta.opensourcebrain.org/ should work now too.
