### ISSUE TITLE
Simulation never finishes.

### ISSUE THREAD

**Issue by Heidecamper** [OpenSourceBrain/geppetto-osb#259]
Dear OSB,

I am still trying to get used to all the features of OSB and am currently stuck on the following:

I attempt to run an experiment of a population that consists of one cell. As input I use 
 <pulseGenerator id="iclamp0" delay="500 ms" duration="200 ms" amplitude="-1 nA"/>
and
<inputList id="Clamps" component="iclamp0" population="pop">
        <input id="0" target="../pop/0/C51A" segmentId="0" destination="synapses"/>
</inputList>
 If I persist the project and run the experiment and as output want the membrane potentials. The simulation never seems to finish. 
![Screenshot from 2019-05-17 14-53-53](https://user-images.githubusercontent.com/45235698/57929716-5b235780-78b4-11e9-9fc9-40755f4450a0.png)

Am I doing something wrong here or is the size of the experiment too large? If there is any other information you need let me know.

**Comment by pgleeson** [comment]
Thanks. We've identified the issue regarding this (Neuron failing mid run and not quitting) and have a fix (https://github.com/NeuroML/org.neuroml.export/commit/bd57ec82076101cc532deb462335d9f3a96cd5fa) which will be put live in the next few days.

**Comment by pgleeson** [comment]
@Heidecamper a fix for this has now been put live, and the simulation should fail (with an error trace containing some details of the issue) rather than run endlessly when there is an error mid simulation.
As mentioned, it's always best to test/debug a new model locally with Neuron before running on OSB
