### ISSUE TITLE
Add option for save only [Ca2+] traces at somas 

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#26]
Aot all segments...

**Comment by mattearnshaw** [comment]
current implementation of recording at soma is a hack that assumes soma instances end with ']' or '_0', which works for HH and others but is not true for eg. DeepLTSFigA2b where both `Seg1_comp_1_1` and `Seg0_comp_1_0` are in the soma_group. Though I don't think there's currently a way to get members of a given segment group via the frontend? @tarelli

**Comment by mattearnshaw** [comment]
implemented at https://github.com/OpenSourceBrain/geppetto-osb/commit/6146b706561cacfca0e3694533d5594f5e247820
