### ISSUE TITLE
Agree on continuos deployment strategy

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/geppetto-osb#261]
- [x] Agree on branches
- [x] Merge code and fixes

**Comment by filippometacell** [comment]
Summary of the meeting: the *development* branch will be used for the staging environment of OSB -> beta.opensourcebrain.org.
The versions of the other related libraries and applications are manually managed through the docker file.
We agreed also to include the redmine application into the build.
The build will be triggered manually on codefresh for now, at some point we can add an automatic trigger (to be defined if on tags or commits).

**Comment by mattearnshaw** [comment]
docker-redmine-osb, docker-osb, and redmine now have PRs for continuous deployment merged to `development` branches
