### ISSUE TITLE
Support ImageSeries data

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/geppetto-osb#263]
- [ ] Look for a file with image in the meta data
- [ ] External link
- [ ] Embedded?

**Comment by filippometacell** [comment]
See https://nwb-schema.readthedocs.io/en/latest/format.html#image-data

**Comment by filippometacell** [comment]
@pgleeson you mentioned an example with an image, could you please link it here?

**Comment by pgleeson** [comment]
I've created an example based on their TwoPhotonSeries example, and added it here: https://github.com/OpenSourceBrain/NWBShowcase/tree/master/NWB (image_series_data.nwb/.py)

It links to an external series of ~80 png images in the gh repo. Might be good for testing the basic retrieval/display of multiple images, but real world examples would be better in the long run.

I've looked as some of the options for embedded images (as datasets), but there seems to be many ways to do it. It might be best to wait for a concrete example of nwb data where the image is embedded to test this. I suspect real world datasets will generally link to external image (and video) files...

**Comment by filippomc** [comment]
Looking at the Python file the linked images are supposed to be on the local path. This opens a new challenge because on order to open the file we need to provide also the images. What about linking with a public url for now?

**Comment by tarelli** [comment]
One thing we did in the past was to look for images in the same path as the main file, this maybe could also be supported?

**Comment by filippomc** [comment]
The main file is imported without any context at the moment, and the local copy is a cache copy of the file alone. We don't really know where those files are unless we import also the file. We may use an archive maybe or a repo (in the context of OSB this would be natural once we use the cache) but for now I think it's easier to use public uris and decide how to import related resources on a second time.

**Comment by pgleeson** [comment]
I'm assuming most people will use a path relative to the generated NWB file in the string pointing to the image, for local testing and then they'll deposit them with the same relative structure. 

It wouldn't be a massive leap to guess:

     images/MyNetwork_T0.png

in a file at

     https://github.com/OpenSourceBrain/NWBShowcase/raw/master/NWB/image_series_data.nwb

translates to 

     https://raw.githubusercontent.com/OpenSourceBrain/NWBShowcase/master/NWB/images/MyNetwork_T0.png

**Comment by filippomc** [comment]
That will work. Moving to NWB explorer repo.

**Comment by tarelli** [comment]
> I'm assuming most people will use a path relative to the generated NWB file in the string pointing to the image, for local testing and then they'll deposit them with the same relative structure.
> 
> It wouldn't be a massive leap to guess:
> 
> ```
>  images/MyNetwork_T0.png
> ```
> 
> in a file at
> 
> ```
>  https://github.com/OpenSourceBrain/NWBShowcase/raw/master/NWB/image_series_data.nwb
> ```
> 
> translates to
> 
> ```
>  https://github.com/OpenSourceBrain/NWBShowcase/raw/master/NWB/images/MyNetwork_T0.png
> ```

What I was thinking
