### ISSUE TITLE
Updates to NWB-E landing page

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#267]
- Add logos for where contributions have come from. Small row at bottom of page with:
    Brought to you by: [OSB logo] [MetaCell logo] [OpenWorm Logo] [Google Summer of code logo] [Wellcome logo]
- Add About (or just "?") button which opens dialog giving some background:
    "The NWB Explorer was initially created by MetaCell to showcase the features of the Geppetto platform to share neurophysiological data in Neurodata Without Borders format. It was further developed by Afonso Pinto as part of a Google Summer of Code project with the OpenWorm project. It is currently being extended as part of the Open Source Brain project to provide both a standalone and online application for visualising and analysing the contents of NWB files. This work is currently funded by the Wellcome Trust." Maybe add links to GH repos?
- Change "Paste a NWB file URL" to "Paste a URL pointing to an NWB file"
- Change to "Ferguson et al. 2015"
- https://github.com/OpenSourceBrain/NWBShowcase/blob/master/TriplettEtAl2018/TriplettEtAl2018.nwb is stable enough to add as a standard example
- Add link "Learn more about the Neurodata Without Borders" pointing to https://www.nwb.org/

**Comment by pgleeson** [comment]
Might also be good to add "beta" somewhere (or even alpha) on the site...

**Comment by filippometacell** [comment]
Hi @pgleeson, this seem straightforward enough to put in place. We only need to decide where to put this information (maybe we can take it small at the bottom). Please let us know if there are any specific costraints on the project requirements side.

**Comment by pgleeson** [comment]
Thanks @filippometacell, see edits to issue above. @tarelli happy for any edits you want to the About text...

**Comment by tarelli** [comment]
Maybe the story can go to the readme in the repo, it's a bit unusual to have something like that inside an application (and to have to maintain it there as it evolves). I'd start maybe with the logo bottom right on the page see how that looks and maybe the question mark opens a tab to the Readme?

**Comment by filippomc** [comment]
Moved here: https://github.com/MetaCell/geppetto-nwbexplorer/issues/23
