### ISSUE TITLE
Test and add new file 

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/geppetto-osb#279]
https://github.com/OpenSourceBrain/NWBShowcase/blob/master/Lantyer/LantyerEtAl2018.170502_AL_257_CC.nwb

Add also other ferguson files (with number buttons on the home page) https://github.com/OpenSourceBrain/NWBShowcase/tree/master/FergusonEtAl2015

**Comment by pgleeson** [comment]
These look good on the live site. Thanks.
