### ISSUE TITLE
Experiment status indicator

### ISSUE THREAD

**Issue by mattearnshaw** [OpenSourceBrain/geppetto-osb#283]
In `react` the indicator on the tab no longer exists. Previously this had been implemented using jquery here: https://github.com/OpenSourceBrain/geppetto-osb/blob/osbDevelopment/ComponentsInitialization.js#L714

and the following change to ExperimentsTable.js:
```
        updateExperimentsTableStatus: function () {
            var self = this;
            var active = window.Project.getActiveExperiment();
            var smallStatus = $('.small-expt-indicator').attr("data-status");
            if (active && smallStatus != active.getStatus()) {
                $('.small-expt-indicator').removeClass(smallStatus);
                $('.small-expt-indicator').addClass(active.getStatus());
                $('.small-expt-indicator').attr("data-status", active.getStatus());
            }
```
However, jQuery is being eliminated from Geppetto. So this feature needs to be rethought.

**Comment by sanjayankur31** [comment]
@pgleeson @filippomc : this looks like something that needs to be kept in mind for OSBv2.

**Comment by filippomc** [comment]
@sanjayankur31 we are moving to netpyne on osb2 for the experimental side so this shouldn't be an issue anymore.

**Comment by sanjayankur31** [comment]
Ah, so netpyne will handle the NSG bits?

**Comment by filippomc** [comment]
The exact definition on the netpyne side is still ongoing, what I'm only sure for now we are not using that code on OSB2

**Comment by pgleeson** [comment]
True, the implementation will be different and experiment status will be handled in a new way in OSBv2. Not relevant anymore.
