### ISSUE TITLE
Add automated UI tests for geppetto-osb

### ISSUE THREAD

**Issue by mattearnshaw** [OpenSourceBrain/geppetto-osb#29]
OSB specific tests
cf. https://github.com/openworm/org.geppetto.frontend/tree/development/src/main/webapp/js/pages/tests/casperjs

**Comment by mattearnshaw** [comment]
in progress @ `casper-tests` branch

**Comment by pgleeson** [comment]
This is more relevant now: https://github.com/OpenSourceBrain/geppetto-osb/issues/295
