### ISSUE TITLE
From AWS to K8s

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/geppetto-osb#290]

**Comment by filippomc** [comment]
The deployment is actually up and running on http://beta.opensourcebrain.org

**Comment by sanjayankur31** [comment]
Is it meant to be publicly accessible? I get: 

```
This site can’t provide a secure connection 

beta.opensourcebrain.org sent an invalid response.

ERR_SSL_PROTOCOL_ERROR
```

**Comment by filippomc** [comment]
Actually the ssl access is an issue to be solved. The actual deployment is http and needs more work to get up and running with https (problems in the communication with geppetto). After trying with https we chose to keep the deployment exactly it as it is for now to speed up the migration process. Leave to you eventually a different choice!
