### ISSUE TITLE
Design new envs on k8s

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/geppetto-osb#291]

**Comment by filippomc** [comment]
Given that only small fixes will be made on the codebase, we can go with 2 environments instead of the classical 3 (test, staging, production).

- *Test/staging environment* - http://comodl.org: continuously deployed on the development branch of every application (redmine, geppetto-osb). When a release is pending, the release branch is deployed instead. Visible on 
- *Production environment* - http://www.opensourcebrain.org: continuously deployed on the master branch of every application. Pushes on the master branch only come from a release branch.

**Comment by pgleeson** [comment]
Sounds good.
