### ISSUE TITLE
Design workspace workflows

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/geppetto-osb#293]
How are resources added to a workspace?
How do applications interact with workspaces?
Can applications see more than one workspace at a time?
How are files managed (loaded, transferred, linked)?
What permission rules on users?
How do workspaces interact with repositories?
Workflow to import/transform files e.g. NeuroML files into netpyne json?
etc.

**Comment by filippomc** [comment]
Following the flow diagram related to importing a resource in the workspace. In green the initial workflow to implement (download from a public url). The repositories are more complex and will come after the first prototype.
![OSB-NetPyNE Architecture - OSB2 data loading (1)](https://user-images.githubusercontent.com/46561561/75890715-08a92c80-5e2f-11ea-97b4-5fc10be70898.png)


> How are resources added to a workspace?
The user can select whether to upload, insert a public url, or take the resource from an existing repository

> How applications interact with workspaces?
Applications see the files of the current workspace locally. The workspace is loaded in read-only mode, so need to interact with the workspace manager api to add/modify files. The application can see also all repositories in read-only mode (to be discussed)

> Can applications see more than one workspace at a time?
No. Only the current workspace is loaded

> How are files managed (loaded, transferred, linked)?
See image above. 

(TO BE CONTINUED)

**Comment by pgleeson** [comment]
@tarelli @filippomc It might be useful to have one shared doc (Google doc maybe) with the definitions of the key terms in OSBv2 at a high level (and maybe links to the design docs in lucidchart)? This can be the one agreed/updated design/definition file independent of charts/issues, etc.

**Comment by filippomc** [comment]
@pgleeson we already have one airtable (invite sent) as a shared document. For now, I'm using this issue for the sake of agree/discuss the key aspects in the meetings before consolidating the design.
