### ISSUE TITLE
Create regression tests for geppetto-osb and redmine features

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/geppetto-osb#295]
Regression tests are functional tests necessary to guarantee the functionality in the release given that who will perform the release does not have historical knowledge of the platform. 

The tests have to be lean and cover the basic functionality.

I propose the following workflow:
- @jrmartin writes the tests based on his understanding of the platform
- @tarelli helps refining the tests
- @pgleeson validates the tests 

Tests can be added to the OSB Airtable and will be manually performed before the releases.

**Comment by pgleeson** [comment]
FYI, a work in progress document listing the core features of the OSBv1 platform: https://docs.google.com/document/d/110FyBMEHlC0chxm-mI8R6pJgITI52t87zj0KxH6nq-A/edit

**Comment by filippomc** [comment]
Thanks, that will be useful

**Comment by filippomc** [comment]
@pgleeson is there a user we can use to login with and perform some tests?

**Comment by pgleeson** [comment]
Just create regular use accounts & you should be able to run simulations etc.

**Comment by pgleeson** [comment]
I can give them admin rights...

**Comment by jrmartin** [comment]
What's an OSB project we can use for testing running of simulations?  

"Run simulation on Neuron OSB
Run sim on Netpyne OSB
Run sim on jnml
Run simulation on Neuron NSG
Run simulation on Netpyne NSG"

**Comment by filippomc** [comment]
@pgleeson

**Comment by pgleeson** [comment]
HHCellSingleAP.net.nml should work: 
http://opensourcebrain.org/projects/hodgkin-huxley-tutorial/models?explorer=https%253A%252F%252Fraw.githubusercontent.com%252Fopenworm%252Fhodgkin_huxley_tutorial%252Fmaster%252FTutorial%252FSource%252FHHCellSingleAP.net.nml

Just testing on nsg now...

**Comment by filippomc** [comment]
Most of the features in the google doc test plan made it to Airtable.
Here's what is missing and why:
- Replay simulations
- Plots move 
- Plot cont activity
- Rasterplots
- Rate plots
Using the ACNET2 project, we can open up each of the widgets above from the 'Results' drop down menu. However, when replaying a simulation, I don't see any other of the 3 widgets plots moving/updating. Using a regular Plot widget, we do see the graph being rendered live as the simulation plays. We didn't add a 'Replay simulation' test for the 3 widgets since we couldn't screenshot what the outcome should look like.

- Tests for Admin section, item (9) on Google Doc: Need admin user to test these.
- Dropbox test: don't have access to the destination Dropbox account to make sure the simulation was saved.
