### ISSUE TITLE
Analyse AWS deployment status

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/geppetto-osb#296]
With this tasks we plan to figure out:
- [x] get credentials
- [x] Deployed branches
- [x] Database status - setup migrate 
- [ ] Stored data status

**Comment by filippomc** [comment]
Dockerfiles

**Comment by filippomc** [comment]
For now, keep user data on the s3 storage

**Comment by zsinnema** [comment]
docker exec -ti docker-osb_mysql_1 /bin/bash
mysql
create user 'user_name'@'%' identified by 'password';
grant all privileges `geppetto`.* to 'user_name'@'%';
flush privileges;

**Comment by sanjayankur31** [comment]
Minor typo there, missed "on geppetto". So, the complete command is:

```
docker exec -ti docker-osb_mysql_1 /bin/bash   # to get into the container
```

Then access the mysql prompt:
```
mysql
```

Then, crate the user and give it privileges:

```
create user 'user_name'@'%' identified by 'password';
grant all privileges on geppetto.* to 'user_name'@'%';
flush privileges;
```

I didn't have a `redmine` user either, so I had to run something similar to create a `redmine` user and then give it privileges on the `redmine` database.

**Comment by zsinnema** [comment]
The redmine user is automatisch creatie via the rocker composer up where the mysql image is build

**Comment by sanjayankur31** [comment]
Ah, I'll double check then. I got permission errors, and going through the same cycle of commands seemed to fix it.
