### ISSUE TITLE
Global switch to white theme

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#30]
Scenes with a white background & white GUI element will be better for screenshots etc. It would be nice to have a single Geppetto console command for changing to this, producing something like:

![selection_198](https://cloud.githubusercontent.com/assets/1556687/24110964/d6b560c2-0d8c-11e7-9a95-c3e526e417bc.png)

**Comment by borismarin** [comment]
See also https://github.com/openworm/org.geppetto.frontend/issues/441

**Comment by mattearnshaw** [comment]
@pgleeson https://gist.github.com/mattearnshaw/102eb47439d43167da847190453b84f6

**Comment by pgleeson** [comment]
Latest version of this: https://gist.github.com/mattearnshaw/c3bd22f70d08ee3d88a78102b8e58334

**Comment by pgleeson** [comment]
@mattearnshaw It would be great if there can be an option to change this easily through the GUI (e.g. button to select white or original shaded theme).

**Comment by pgleeson** [comment]
Done
