### ISSUE TITLE
tear down "old" aws server(s) and spin up new google cloud servers

### ISSUE THREAD

**Issue by zsinnema** [OpenSourceBrain/geppetto-osb#303]
- [ ] keep S3 bucket
- [ ] check that the redirect is still working so nobody can change anything
- [ ] change dns records
- [ ] check that if everything is working

**Comment by filippomc** [comment]
Setup redirect from www.opensourcebrain.org to opensourcebrain.org

**Comment by zsinnema** [comment]
done via ingress config
`      nginx.ingress.kubernetes.io/from-to-www-redirect: "true"`

**Comment by filippomc** [comment]
@zsinnema why was this closed?

**Comment by zsinnema** [comment]
sorry, accidentally closed ;-)
