### ISSUE TITLE
SSL certificates for k8s GC

### ISSUE THREAD

**Issue by zsinnema** [OpenSourceBrain/geppetto-osb#305]
Create & install SSL certificates for 
- [ ] opensourcebrain.org
- [ ] www.opensourcebrain.org
- [ ] geppetto.opensourcebrain.org (??? not sure, this one can also be hosted, reversed proxy, on the above hosts)

**Comment by filippomc** [comment]
letsencrypt + ingress. 
To do: map the addresses above for testing

**Comment by filippomc** [comment]
This is ready, still we need to fix something on application side to get it work with ssl. See #310

**Comment by zsinnema** [comment]
done via ingress config
`      nginx.ingress.kubernetes.io/configuration-snippet: |
        proxy_set_header      Origin "";`
