### ISSUE TITLE
Change in GitHub repo not updated in beta site mirror copy

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#312]
A change in the contents of the GH repos for OSB project should be reflected when the corresponding OSB repo page is (re)loaded, e.g. README here out of sync
https://github.com/OpenSourceBrain/OpenCortex
http://beta.opensourcebrain.org/projects/opencortex/repository

This used to be enabled by a webhook on the GH side, but not any more. @sanjayankur31 Can you dig into the redmine code and see where these pages ask for the latest copy of the repo contents and updates the mirrors in /home/svnsvn/myGitRepositories?

**Comment by sanjayankur31** [comment]
@pgleeson : this was sorted, right? Just needed the repos to be cloned properly on beta? Please close if confirmed.

**Comment by zsinnema** [comment]
I think so too once we switch of AWS and move the GC to the opensourcebrain.org domain and copied all repos from AWS to GC it should work

**Comment by pgleeson** [comment]
The immediate problem of the repos not updating on beta is fixed, so will close.
