### ISSUE TITLE
Get submit to NSG working on beta site

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#317]
e.g. get "Neuron on NSG" working.

<img width="451" alt="Screenshot 2020-04-16 at 12 48 55" src="https://user-images.githubusercontent.com/1556687/79452849-b851ec80-7fe0-11ea-95b1-a26efd98b078.png">

Note: currently simulations on NSG are taking >12 hrs to complete... But should nonetheless get submitted successfully (i.e. change to yellow)

Settings for NSG are added here: https://github.com/SilverLabUCL/docker-osb/blob/master/dockerFiles/simulator-config.xml

**Comment by pgleeson** [comment]
For @zsinnema; needs to add variables in codefresh for simulator-config.xml

**Comment by zsinnema** [comment]
I've added the additional params to the docker-compose and build_all.sh (feature/cd_changes)

**Comment by pgleeson** [comment]
FYI @zsinnema NSG jobs are taking longer than ever, but will test this...

**Comment by pgleeson** [comment]
Jobs are now getting submitted to NSG from beta, and running there successfully. They're not showing up as completed in the model list though, showing as ERROR. Invetsigating further...

**Comment by pgleeson** [comment]
Working! NSG jobs are returning within 5 mins now, and can be reloaded & plotted just like locally run jobs.
