### ISSUE TITLE
Enable global minimum diameter for segments

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#32]
To render this better:

![selection_261](https://cloud.githubusercontent.com/assets/1556687/25481075/6fc0b3e2-2b43-11e7-8d12-cea5a3951d0d.png)

Original comment from https://github.com/OpenSourceBrain/geppetto-osb/issues/27:

"impose a minimum radius for cylinders, so that model is still legible when zoomed out... this would require redrawing cylinders at each zoom level, if the effect is to be smooth (since cylinder radii are fixed). perhaps impose max/mindistance on getVARS().controls instead?"

As discussed with @tarelli, it would be simpler (initially at least) if this can just be changed by a global parameter minimalDiameterCylinders (or something) that is general to Geppetto and can be changed in the console to improve viewing of thin dendrites

**Comment by mattearnshaw** [comment]
a version of this is on live, in the `livemix` branch currently. 

syntax: `network.setGeometryType('cylinders', minRadius, maxRadius)` where both params optional.

**Comment by pgleeson** [comment]
Done
