### ISSUE TITLE
Set up SPF record

### ISSUE THREAD

**Issue by sanjayankur31** [OpenSourceBrain/geppetto-osb#327]
The most probably cause is that no SPF is defined for opensourcebrain.org. Here are the headers from an e-mail, for example:

From info AT opensourcebrain.org Tue Mar 31 16:23:59 2020
...
Authentication-Results: spf=none (sender IP is xxxxx)
 smtp.mailfrom=opensourcebrain.org; something.co.uk; dkim=none (message not
 signed) header.d=none;something.co.uk; dmarc=none action=none
 header.from=opensourcebrain.org;compauth=fail reason=001
Received-SPF: None (protection.outlook.com: opensourcebrain.org does not
 designate permitted sender hosts)
...

This needs to be looked into. The DNS records need updating.

Reference:

https://en.wikipedia.org/wiki/Sender_Policy_Framework
https://unix.stackexchange.com/questions/81438/mails-being-marked-as-spam
There are lots of HowTos on how to do this, but perhaps our DNS provider will provide specific instructions.

**Comment by sanjayankur31** [comment]
I've set one up. Will test it in 24 hours once DNS has synced up:

https://easydmarc.com/tools/spf/opensourcebrain.org?domain=opensourcebrain.org

**Comment by sanjayankur31** [comment]
Seems to have worked:

```
Authentication-Results: spf=pass ....
Received-SPF: Pass (protection.outlook.com: domain of opensourcebrain.org
 designates xxxx as permitted sender)
 receiver=protection.outlook.com; client-ip=xxxx;
...
 ```

Closing.

**Comment by pgleeson** [comment]
Great, thanks!
