### ISSUE TITLE
Migrate Codefresh pipeline to use new registry

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/geppetto-osb#334]
The codefresh registry will be shut down. We switch to google cloud registry.

**Comment by filippomc** [comment]
Building in the new registry now, need to change the k8s files

**Comment by zsinnema** [comment]
fixed in branch https://github.com/SilverLabUCL/docker-osb/tree/feature/cd-changes

**Comment by zsinnema** [comment]
fixed in branch https://github.com/SilverLabUCL/docker-osb/tree/feature/cd-changes
