### ISSUE TITLE
Investigate connectivity issues between redmine and geppetto

### ISSUE THREAD

**Issue by sanjayankur31** [OpenSourceBrain/geppetto-osb#335]
We're seeing some intermittent issues where updates to user profiles on redmine are not propagating correctly to geppetto. This results in user not being able to access the geppetto explorer correctly.

**Comment by pgleeson** [comment]
I believe this is fixed now. Changed the hostname to opensourcebrain.com inside redmine in docker-compose.yml. Tried it with a new user...

**Comment by sanjayankur31** [comment]
Yay. Closing.
