### ISSUE TITLE
Set up status.opensourcebrain.org

### ISSUE THREAD

**Issue by sanjayankur31** [OpenSourceBrain/geppetto-osb#338]
We should have a "status" website that users can refer to for quick checks. We can even list "known issues" etc there so our users are aware of existing bugs that we're working on. And, it'll be very useful to announce infrastructure outages, for example when we move from AWS to GC etc. When OSBv2 is ready, this can also show the status of the various bits etc.

Something light that can be manually updated perhaps, we don't want any monitoring tools that we'll have to administer (and which would require infra to run either). And I assume, it should be hosted on different infra than OSB itself, so that if OSB goes down, the status website remains up---Github pages perhaps?

@filippomc @tarelli @zsinnema : are you folks already using something at metacell that we should also set up?

Found a few static ones:

- https://github.com/cstate/cstate
- https://github.com/Lugribossk/simple-dashboard
- https://github.com/fedora-infra/statusfpo is what Fedora infrastructure uses for https://status.fedoraproject.org (although they use Nagios to monitor their infra also, so I'll have to check if it's fully static).

**Comment by pgleeson** [comment]
In progress here: https://github.com/OpenSourceBrain/ServiceStatus

**Comment by sanjayankur31** [comment]
It's up: https://opensourcebrain.github.io/ServiceStatus/

Setting up the subdomain now.

**Comment by sanjayankur31** [comment]
We're live at http://status.opensourcebrain.org/
