### ISSUE TITLE
All users see the latest projects under "Your projects"

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#339]
e.g.
<img width="1343" alt="Screenshot 2020-07-29 at 17 08 02" src="https://user-images.githubusercontent.com/1556687/88824303-17b5c000-d1be-11ea-9201-a7b5bca121a4.png">

**Comment by sanjayankur31** [comment]
This was by design: the list included projects that were visible to the user first, and then the user's projects. I've removed the first bit and will open a PR when I've tested it out.
