### ISSUE TITLE
Switch production to kubernetes/google cloud deployment

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/geppetto-osb#340]
- [x] Fix last issues
- [x] Wrap up dedicated meeting
- [x] fix osb1 codefresh deployment with new k8s version
- [x] Migrate to other cluster
- [x] Performance tuning
- [x] Migrate database
- [x] Switch s3 bucket from dev to prod
- [x] Move repositories in the redmine fs
- [x] Switch DNS

**Comment by filippomc** [comment]
Migrate wrap up:

- Letsencrypt change name
- Redeploy, test
- Communicate ip to padraig

**Comment by zsinnema** [comment]
letsencrypt: done see https://github.com/MetaCell/cloud-harness/issues/86
redeploy done
new ip: 35.193.217.156 is communicated with Padraig

**Comment by filippomc** [comment]
Performance issue may be related with using S3 buckets from Google cloud?
Matteo: may be a bandwidth problem.

**Comment by pgleeson** [comment]
Done!
