### ISSUE TITLE
Test osb1 builds and pipelines

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/geppetto-osb#349]
- [ ] Test and eventually fix docker images for geppetto and redmine
- [ ] Do a deployment on beta

**Comment by zsinnema** [comment]
Hi @filippomc I was able to fix some issues with the Docker build but now I'm stuck here:
![image.png](https://images.zenhubusercontent.com/5e2079d495a332382cd766a5/611eac95-fb00-46d4-b96a-9e437bb30bad)

the issue here is that this doesn't work: `git ls-remote -h -t git://github.com/uditalias/superagent-no-cache.git` imo it should be like this: `git ls-remote -h -t https://github.com/uditalias/superagent-no-cache.git`

so `https://` instead of `git://`

any thoughts

**Comment by zsinnema** [comment]
I pushed the changes on the Dockerfile here: https://github.com/SilverLabUCL/docker-osb/tree/feature/349

**Comment by zsinnema** [comment]
@pgleeson I had to freeze some packages (see line 75): pynn==0.9.6 netpyne==0.9.6 pyneuroml==0.5.11 quantities==0.12.5 neuromllite==0.3.4 because of non existing dependent packages for Python2.7

are the assumptions of the versions correct?

**Comment by zsinnema** [comment]
@pgleeson I had to freeze some packages (see line 75): pynn==0.9.6 netpyne==0.9.6 pyneuroml==0.5.11 quantities==0.12.5 neuromllite==0.3.4 because of non existing dependent packages for Python2.7

are the assumptions of the versions correct?

**Comment by pgleeson** [comment]
@zsinnema Yes, those look correct from logging on to geppetto and running `pip list`. I think there was a start at updating it to python 3, but best get it rebuilding/redeploying with the curent configuratio for now before updating.

**Comment by filippomc** [comment]
create a pipeline to update only the redmine application first

**Comment by filippomc** [comment]
Redmine docker file: https://github.com/SilverLabUCL/docker-redmine-osb/blob/development/Dockerfile
Redmine app branch: master

Geppetto docker file: https://github.com/SilverLabUCL/docker-osb/blob/feature/cd-changes/Dockerfile

Geppetto is built on those branches: 
ENV BRANCH_BASE=development
ENV BRANCH_DEFAULT=v0.4.1-alpha
ENV BRANCH_ORG_GEPPETTO=$BRANCH_DEFAULT
ENV BRANCH_ORG_GEPPETTO_CORE=livemix
ENV BRANCH_ORG_GEPPETTO_MODEL=$BRANCH_DEFAULT
ENV BRANCH_ORG_GEPPETTO_FRONTEND=geppetto-osbv1
ENV BRANCH_ORG_GEPPETTO_MODEL_SWC=$BRANCH_DEFAULT
ENV BRANCH_ORG_GEPPETTO_MODEL_NEUROML=pg_temp_nml1.7.1
ENV BRANCH_ORG_GEPPETTO_PERSISTENCE=$BRANCH_DEFAULT
ENV BRANCH_ORG_GEPPETTO_SIMULATION=livemix
ENV BRANCH_ORG_GEPPETTO_SIMULATOR_EXTERNAL=osbDevelopment
ENV BRANCH_GEPPETTO_OSB=osbDevelopment
