### ISSUE TITLE
Plot all recorded variables not working in live

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#37]
For a completed simulation, the "Plot all recorded variables" option is not working in live. It seems to work after one variable has been plotted with the control panel.

**Comment by pgleeson** [comment]
Also an issue in my local version based on development branches. It seems that once a plot is created manually through the control panel then it's added to 'all recorded variables' and will be plotted once "Plot all recorded variables"  is pressed.

Maybe related... I've only recorded 2 state vars, but all are shown when I press **x<sup>2</sup>** in the control panel:

![selection_263](https://cloud.githubusercontent.com/assets/1556687/25902743/590c4734-3592-11e7-8908-14c75d413ec3.png)

**Comment by mattearnshaw** [comment]
unable to replicate former issue, see https://github.com/openworm/org.geppetto.frontend/issues/599 for latter

**Comment by pgleeson** [comment]
Both of these still an issue on comodl...

![selection_283](https://user-images.githubusercontent.com/1556687/26838572-65f6943a-4ad8-11e7-8f2f-e702fdc3c1e0.png)

I just saved v at soma; hit "Plot all recorded variables"; empty plot came up; opened control panel; all segments listed under x^2, but only (Add)Plot icon for soma; plotted soma; new plot appeared & previous plot filled in with trace for v...

**Comment by tarelli** [comment]
@pgleeson I merged a fix to development this morning (part of the release) @mattearnshaw we need to update comodl to the latest and retest this

**Comment by mattearnshaw** [comment]
seems fine on comodl. @pgleeson could you double check? I don't think I've ever been able to replicate the empty plot thing

**Comment by mattearnshaw** [comment]
fix and test awaiting merge above, this was an issue in `org.geppetto.simulation`

**Comment by pgleeson** [comment]
Still broken in development branches...

**Comment by mattearnshaw** [comment]
broke for a different reason, fixed with latest commit to geppetto-osb/`color-options2`
