### ISSUE TITLE
Id of network should be used as name of top level Geppetto object, not name of file

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#4]
e.g. in this example: http://www.opensourcebrain.org/projects/hodgkin-huxley-tutorial/repository?explorer=https%253A%252F%252Fraw.githubusercontent.com%252Fopenworm%252Fhodgkin_huxley_tutorial%252Fmaster%252FTutorial%252FSource%252FHHCellVClamp.net.nml#

the network is defined with:

```
 <network id="HHCellNetwork">
```

but since the file is called [HHCellVClamp.net.nml](https://github.com/openworm/hodgkin_huxley_tutorial/blob/master/Tutorial/Source/HHCellVClamp.net.nml), the Geppetto object is called HHCellVClamp e.g.

```
 HHCellVClamp.hhpop[0].v
```

Ideally, and for many curated projects, the id will match the file name of the main network, but the file name is arbitrary and the id is the unique string for the network.

**Comment by pgleeson** [comment]
Checked and still an issue. Would be good for consistency if this was changed. @mattearnshaw can you have a look when you get a chance?

![selection_260](https://cloud.githubusercontent.com/assets/1556687/25480723/f7481fa0-2b41-11e7-8770-af5bde06fa10.png)

**Comment by mattearnshaw** [comment]
can't work this out, @tarelli do you have an intuition about where the filename is sneaking in? the type name/id is correct...

**Comment by tarelli** [comment]
@mattearnshaw I'll have a look and get back to you

**Comment by mattearnshaw** [comment]
@tarelli nvm
