### ISSUE TITLE
Test latest release on Firefox

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#44]
Getting a number of errors testing comodl on Firefox on Mac & Linux, from old favourite
![selection_273](https://cloud.githubusercontent.com/assets/1556687/26692007/11813ec6-46f7-11e7-826c-a2dd37668f1e.png)

(viewing a standard project network, which works in the browser on live) to split screen. 

Front page example Acnet does load Geppetto on Firefox but no cells:

![selection_274](https://cloud.githubusercontent.com/assets/1556687/26692127/77a20514-46f7-11e7-9b7b-8733f67621ec.png)

**Comment by tarelli** [comment]
![screen shot 2017-06-01 at 18 27 30](https://cloud.githubusercontent.com/assets/81127/26692272/fce4ab00-46f7-11e7-9c23-467c16f1ed2f.png)

**Comment by tarelli** [comment]
@pgleeson have you tried clearing cache and refreshing? Shows fine in Firefox here, will keep testing anyway

**Comment by tarelli** [comment]
@pgleeson btw dont use the samples, they all need to be updated...

**Comment by pgleeson** [comment]
Seems to be all fine on Firefox now. 
Any way to enforce refreshing of the relevant parts of the cache when a new Geppetto version is used..?
