### ISSUE TITLE
Reformat page for "More" on OSB projects

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#45]
Currently:

![selection_281](https://user-images.githubusercontent.com/1556687/26836926-1737435c-4ad4-11e7-8d57-9e8f3f5924b3.png)

Should be nicely formatted page with columns for Sessions, Networks, Cells, etc. 
Buttons for each individual file

**Comment by mattearnshaw** [comment]
some pages eg. celegans have hundreds of files, unevenly distributed across networks/channels/etc., so this should be taken into account in any design. I have pushed a redesign to comodl that includes a filter box for searching: http://comodl.org/projects/celegans/models

**Comment by pgleeson** [comment]
Looks good, but an alternative would be to have 1-6 columns (depending on which of session/network/cell/channel/synapse/other were present) evenly spaced horizontally along the page with the pre expanded list of entries going down the page. The default from _osb.yml could be highlighted. Then for most models all the files will be quickly visible/clickable.

**Comment by mattearnshaw** [comment]
"Click star to save and enable simulation" is shown on load https://github.com/OpenSourceBrain/geppetto-osb/commit/b463e7c5bee8c6ad9694903a492f722f95b34e85
