### ISSUE TITLE
Update connectivity matrix with coloured bars on top/side for pre/post population

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#48]
The connectivity matrix curently requires interactive hovering over the squares to see which is the pre/post population. This would be easier to see at first glance if there was a thin coloured bar above and to the left of the matrix with the appropriate colour of the population (this may only be possible when the "Order by: Entity name" is selected):

![selection_291](https://user-images.githubusercontent.com/1556687/27089616-d16216a2-5052-11e7-86b9-3dcc71eff26c.png)

It's much easier to see here with the outer rim/list of populations:

![selection_292](https://user-images.githubusercontent.com/1556687/27089675-03257a26-5053-11e7-8dd2-963568bdbe74.png)

http://www.opensourcebrain.org/projects/nc_ca1?explorer=https%253A%252F%252Fraw.githubusercontent.com%252Fmbezaire%252Fca1%252Fmaster%252FNeuroML2%252Fnetwork%252FHippocampalNet.net.nml#

**Comment by mattearnshaw** [comment]
in progress @ frontend `matrix-pre-post` branch
