### ISSUE TITLE
Redmine refactor tweaks

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#50]
- [x] Images missing on http://www.opensourcebrain.org/projects#cells & http://www.opensourcebrain.org/projects#technology
- [x] editing of custom fields when admin, e.g. http://www.opensourcebrain.org/projects/ca3-pyramidal-cell/settings and click on Custom fields at bottom
- [x] Clicking on "breadcrumb trail" on project page (e.g. Rodent) used to go back to the tree view in explore with the appropriate node selected, but it doesn't now
- [x] "Your projects" and "Latest projects added on OSB" empty on homepage when logged in
- [x] Check double listing of user names in groups view: http://comodl.org/groups/11

**Comment by pgleeson** [comment]
- [ ] Edit group page: http://www.opensourcebrain.org/groups/11/edit#tab-content-general, http://www.opensourcebrain.org/groups/11/edit

**Comment by mattearnshaw** [comment]
should be all up to date, new issues can go on new issues
