### ISSUE TITLE
People page slow to load

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#53]
http://comodl.org/projects#people

Is it still the case that all of people/groups/technology is loaded in the background when this page loads?

**Comment by pgleeson** [comment]
This is still an issue... 
Going to http://www.opensourcebrain.org/projects, then clicking on People takes ~15 secs, however going directly to http://www.opensourcebrain.org/projects#people is much quicker...

**Comment by mattearnshaw** [comment]
these are now on par
