### ISSUE TITLE
Reenable SWC visualisation

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#57]
It used to be possible for Geppetto to find SWC files in a github repo on OSB and visualise these with the SWCInterpreter in the same way as NML2. This seems to be broken in live and comodl...

http://www.opensourcebrain.org/projects/neuromorpho
http://www.opensourcebrain.org/projects/test_demo_osb/repository/revisions/master/show/SWC
http://comodl.org/projects/neuromorpho/models

**Comment by mattearnshaw** [comment]
fixed on comodl (https://github.com/OpenSourceBrain/redmine/commit/26ad048c30c373a4f690768a1ee5334739da07f6)
