### ISSUE TITLE
Add seed & temperature in Run options dialog

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#63]
Should eventually be passed to LEMS file as in https://github.com/NeuroML/NeuroML2/blob/master/LEMSexamples/LEMS_NML2_Ex16_Inputs.xml#L57 (is automatically used in generated simulation scripts)

This will allow the same neuroml file with stochastic inputs to be run multiple times giving different results.

**Comment by pgleeson** [comment]
Also need to be able to specify temperature...

**Comment by pgleeson** [comment]
Temperature less of a priority, but could be done at same time...
There should also be a way to see what temp/seed was used during specific experiments... maybe extend the table in the experiment view (or add them to the list of "set" parameters that show up)

**Comment by mattearnshaw** [comment]
expt table is currently being extracted as a component, will only be able to extend it when that is done. for now, experiment name can be used.

**Comment by pgleeson** [comment]
Done
