### ISSUE TITLE
Opening model from repository listing page leaves contents of OSB page on top of Geppetto

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#65]
Go to: http://www.opensourcebrain.org/projects/hodgkin-huxley-tutorial/repository/revisions/master/show/Tutorial/Source

Click on one of the green eyes to visualise that cell/network, e.g. HHCellNetwork.net.nml and...

![selection_348](https://user-images.githubusercontent.com/1556687/28885540-2c54e31e-77ae-11e7-9939-df7d99435260.png)

**Comment by mattearnshaw** [comment]
fixed + live (redmine)
