### ISSUE TITLE
HH tutorial page broken

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#66]
Link on  http://www.opensourcebrain.org/tutorials 

Correction, it goes to page showing sphere, but need to zoom out to see it.

No HH specific tutorial info dialog is shown...

**Comment by mattearnshaw** [comment]
https://github.com/openworm/org.geppetto.frontend/issues/667

**Comment by mattearnshaw** [comment]
waiting for @tarelli to merge https://github.com/tarelli/tutorials/pull/2

**Comment by tarelli** [comment]
Merged

**Comment by mattearnshaw** [comment]
thanks!
