### ISSUE TITLE
Add option to use soma v for whole cell when coloring

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#7]
Maybe add in drop down menu:

```
Apply voltage colouring to morphologies (use soma voltage for whole cell)
```

**Comment by mattearnshaw** [comment]
implemented in `cell-light` branch, though need to fix UI bug (radio button behaviour of colouring options)

**Comment by pgleeson** [comment]
@mattearnshaw Shouldn't this option be showing up in the dropdown in live now?

**Comment by mattearnshaw** [comment]
@pgleeson it's still at https://github.com/OpenSourceBrain/geppetto-osb/pull/41. I haven't pushed for it to be merged since there were some intervening API changes that meant it needed revision and testing - will do that this afternoon

**Comment by pgleeson** [comment]
Thanks @mattearnshaw. Would it be possible to get this on comodl by tomorrow afternoon (if you feel it's stable)? Would be nice to show a large network demo with all cells lighting up. Thanks.
