### ISSUE TITLE
Issue plotting protocol results

### ISSUE THREAD

**Issue by gidili** [OpenSourceBrain/geppetto-osb#73]
Was testing protocols today on osb (main depoyment) and noticed that everything is working fine up until the point you try to plot results. See errors below upon clicking the "plot data" button.

![screenshot 2017-11-14 16 22 45](https://user-images.githubusercontent.com/68134/32792466-535c43e0-c95b-11e7-9db4-5fc7653d8eac.png)

![screenshot 2017-11-14 16 18 11](https://user-images.githubusercontent.com/68134/32792485-5b7da0fa-c95b-11e7-916e-70bcc46edf53.png)

![screenshot 2017-11-14 16 18 51](https://user-images.githubusercontent.com/68134/32792477-56742598-c95b-11e7-9bf0-577260eab1fa.png)

Possibly something to do with latest geppetto changes and async stuff.

@mattearnshaw can you test and see if you get the same?

**Comment by mattearnshaw** [comment]
@gidili thanks. this https://github.com/OpenSourceBrain/geppetto-osb/commit/7c4f7b8ff0d8adf616d002d33cb07bae972a05b2 fixes the plotting issue (can you confirm?), although I still need to sort out the `widget.getId` errors (related to form widget not being an `AbstractComponent`: my attempt here failed https://github.com/openworm/org.geppetto.frontend/commit/945db505e75a208fba799258fb7edd9fb37b186b)

**Comment by gidili** [comment]
@mattearnshaw did you re-deploy with the fix? I was testing on www.opensourcebrain.org/ as I am not on my dev machine

**Comment by mattearnshaw** [comment]
@gidili have also deployed the fix on osb.org.

**Comment by gidili** [comment]
@mattearnshaw all good now after clearing cache, thanks for the quick fix!

![screenshot 2017-11-14 17 53 46](https://user-images.githubusercontent.com/68134/32795826-d601f8f4-c964-11e7-951e-fbc1f4561fff.png)
