### ISSUE TITLE
All projects are reported to have 3MB

### ISSUE THREAD

**Issue by borismarin** [OpenSourceBrain/geppetto-osb#75]
After clicking on 'Explore Model' for any project (well, at least the half dozen I've tried), the message `LOADING... [~3MB]` pops up. The size seems to be hardcoded to 3MB, regardless of the project.

<img width="1437" alt="screen shot 2017-11-17 at 14 25 10" src="https://user-images.githubusercontent.com/3452783/32957570-3a17a830-cba3-11e7-88b1-39c38535c65d.png">
<img width="1435" alt="screen shot 2017-11-17 at 14 24 43" src="https://user-images.githubusercontent.com/3452783/32957571-3a37c520-cba3-11e7-8d91-0791dea4a551.png">

**Comment by tarelli** [comment]
@borismarin it's not the size of the project, it's the size of the core Geppetto library

**Comment by borismarin** [comment]
d'oh!

2017-11-17 14:29 GMT-02:00 Matteo Cantarelli <notifications@github.com>:
