### ISSUE TITLE
Connectivity matrix showing synaptic weights

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#78]
Colouring scaled (blue->red) by total synaptic weight between pairs of cells, aot one colour for all connections in projection between pre/post populations

**Comment by mattearnshaw** [comment]
on comodl…

**Comment by pgleeson** [comment]
To double check for current based synapses

**Comment by pgleeson** [comment]
Working, but could be enhanced with 

- [ ] when weights are !=1 add specific weight in text when connection square is hovered over: PopA[0] is connected to PopB[1] (weight=2)
- [ ] needs to be checked that it works with 1) gap junctions, 2) continuous connections, both of which can have weights

**Comment by mattearnshaw** [comment]
moved to https://github.com/OpenSourceBrain/geppetto-osb/issues/120
