### ISSUE TITLE
Keep displayed plots open when switching between experiments

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#80]
Think this may be elsewhere too...

**Comment by pgleeson** [comment]
This will be a crucial feature when using the tutorials & running multiple simulations...

**Comment by mattearnshaw** [comment]
testing at https://github.com/openworm/org.geppetto.frontend/commit/7b974b46e719c21bfd9f73a2f35c530333d458a0

**Comment by mattearnshaw** [comment]
fixed on live now.
