### ISSUE TITLE
Better user interaction with Results/Run menus

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#88]
![selection_463](https://user-images.githubusercontent.com/1556687/33957186-d3d6dd8e-e038-11e7-91a6-a84969068a40.png)

Results and Run buttons/menus are sometimes annoying and can stay open too long. Suggestions for improvements (and prob applies to any new drop down menu):
- close/retract the menu when an item in it is selected (e.g. play step by step)
- close them when another button is pressed
- These should probably be disabled until project is persisted

**Comment by mattearnshaw** [comment]
on comodl / `development`…
