### ISSUE TITLE
Ability to use radius from annotation in NeuroML file for abstract cells

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#9]
Many abstract cells in NeuroML2 have no 3D information, e.g. I&F, Izhikevich, specifically nothing saying what radius the should be when rendered in 3D. 

The default for this in OSB is to use 1um, as this has been useful for the C elegans model, e.g. [here](http://opensourcebrain.org/projects/celegans?explorer=https%253A%252F%252Fraw.githubusercontent.com%252Fopenworm%252FCElegansNeuroML%252Fmaster%252FCElegans%252FpythonScripts%252Fc302%252Fexamples%252Fc302_A_Muscles.nml#) since this appropriate for the radius for somas in the worm.

Ideally the default should be 5um, but this could be overridden [in the `<population>` element](https://github.com/openworm/CElegansNeuroML/blob/master/CElegans/pythonScripts/c302/examples/c302_B_Muscles.nml#L59) in the neuroml file inside an `<annotation>` (similar to https://github.com/OpenSourceBrain/redmine/issues/244) allowing different networks to customise how they are displayed.

**Comment by mattearnshaw** [comment]
initial implementation on frontend & model.neuroml `radius` branches, working with eg. https://github.com/mattearnshaw/NeuroMLTesting/blob/master/CElegans/pythonScripts/c302/examples/temp_test/c302_C1_Muscles.net.nml#L771

**Comment by mattearnshaw** [comment]
https://github.com/openworm/org.geppetto.frontend/pull/624
