### ISSUE TITLE
Use colour of population as default colour when plotting cell traces

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#92]
For example [this](http://www.opensourcebrain.org/projects/izhikevichmodel/models?explorer=https%253A%252F%252Fraw.githubusercontent.com%252FOpenSourceBrain%252FIzhikevichModel%252Fmaster%252FNeuroML2%252FIzh2007Cells.net.nml) would be much clearer when run & Plot all recorded variables pressed if they had same colours as cell populations:

![image](https://user-images.githubusercontent.com/1556687/34222457-8374f490-e5b3-11e7-9d9d-f429fe70f08e.png)

**Comment by mattearnshaw** [comment]
https://github.com/OpenSourceBrain/geppetto-osb/commit/7901c98f17052734c0da69f4c8c9911faf230fbb
https://github.com/openworm/org.geppetto.frontend/commit/a500e207a9378dada38d78aa993b14165e1c49df
