### ISSUE TITLE
Errors when plotting (in)activation variables

### ISSUE THREAD

**Issue by borismarin** [OpenSourceBrain/geppetto-osb#97]
- [x] ~~L23 example (BlueBrain showcase) -> model description -> Ca_HVA -> plot h
(seems to be broken for every other channel as well): results in blank screen due to
```Uncaught TypeError: G.addWidget(...).plotFunctionNode is not a function```.~~
Fixed by https://github.com/OpenSourceBrain/BlueBrainProjectShowcase/commit/fe2041a1d99ee7554d8f7841bfabb1fa7269acc0

- [x]  ~~HH example -> Na channel -> plot alpha_m: empty plot canvas due to Uncaught (in promise) TypeError: Unsupported type of condition "Array"~~
Fixed by https://github.com/openworm/org.geppetto.frontend/pull/739

**Comment by mattearnshaw** [comment]
first problem was due to old code stored in strings of the state for sample projects: https://github.com/OpenSourceBrain/IzhikevichModel/commit/a3d1856aff92073498696575e3dc2395f3f79a44

this is not very nice to debug! we should be able to avoid this

**Comment by borismarin** [comment]
Was the Izhikevich sample interfering with L23 then?

**Comment by mattearnshaw** [comment]
@borismarin 3 of the sample projects had this bug incl. L23 and Izh

**Comment by borismarin** [comment]
OK - updating first msg with commit info.

**Comment by mattearnshaw** [comment]
got the second one there
