### ISSUE TITLE
Add search results for NeuroML-DB when searching on OSB

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#98]
Search results on OSB are limited to text in projects. It would be better to include results from NeuroML-DB in these search result pages, which have links back to OSB, e.g. compare

http://www.opensourcebrain.org/search?utf8=%E2%9C%93&projects=1&q=delayed+rectifier
https://neuroml-db.org/search_model?q=delayed%20rectifier

@scrook @JustasB this can be a first concrete step to greater interaction between these. Is there a RESTful API by any chance?

**Comment by JustasB** [comment]
I've been working on a REST API for another unrelated project for NML-DB. Currently, the (dev) api supports getting the list of all NML-DB models and getting the details of a model. What functionality would you need? It would help me the most if you specified an interface you would like implemented. I could have this released after I'm done with the Migliore model.

CC @scrook

**Comment by pgleeson** [comment]
The main functionality required (for this) would be to post a search term to the NML-DB API and get back a list of the search results, containing the 3 items you get on the summary page like https://neuroml-db.org/search_model?q=delayed%20rectifier, i.e. name, url and main model reference. This could be formatted & displayed inside osb (on the search results page in an area below clearly marked that they're from nmldb), and anyone hitting the link would open a new tab with the nmldb page open.

So no api command for getting the full details of the model is required for now...

**Comment by JustasB** [comment]
@pgleeson Take a look at the dev version of the API that returns a JSON list of models matching a keyword query: http://spike.asu.edu:5000/api/search?q=delayed%20rectifier

There are a few other api methods you can use if needed: http://spike.asu.edu:5000/api

Let me know if this will work for you. I can let you know when the API is ready on the production site.

**Comment by mattearnshaw** [comment]
initial version
http://opensourcebrain.org/search?utf8=✓&projects=1&neuroml_DB=1&q=delayed+rectifier

**Comment by JustasB** [comment]
FYI, the search web service is now available on our production server. The testing server url:
`http://spike.asu.edu:5000/api/search?q=delayed%20rectifier`

can be now be replaced with:
`https://neuroml-db.org/api/search?q=delayed%20rectifier`

@pgleeson @mattearnshaw @scrook

**Comment by mattearnshaw** [comment]
thanks @JustasB.
